### ISSUE TITLE
Unexpected token . on line 88

### ISSUE THREAD

**Issue by mokahless** [Areha11Fz/HoYoLAB-Auto-Check-In#2]
Attempting to run this with node on ubuntu 22 and getting this error. Set up my tokens, set to genshin only on and set discord to false.

```
user@system:~/hoyolab-auto-check-in$ node autoDailyCheckIn.js
/home/user/hoyolab-auto-check-in/autoDailyCheckIn.js:88
                ?.replace(/_/g, " ");
                 ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by Areha11Fz** [comment]
I only tested it on google script https://script.google.com/home , I haven't tried it on node js
